export const INCIDENT_ALLOWANCE_STANDARD_RATE = 17.3;
export const INCIDENT_ALLOWANCE_REDUCED_RATE = 13;
export const INCIDENT_ALLOWANCE_STANDARD_DAYS = 30;

export const TRIP_DISTANCE_DEBOUNCE_MS = 1000;

export const DEFAULT_DEPARTURE_TIME = '12:00';
export const DEFAULT_RETURN_TIME = '15:00';
